ab_cu_t/urls.py
from django.urls import path
from . import views

app_name = 'ab_cu_t'

urlpatterns = [
    path('faq/', views.faq_page, name='faq_page'),
    path('PrivacyPolicy/', views.privacy_policy, name='privacy_policy'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('contact/', views.contact_us_page, name='contact_us_page'),
]

domain_check/urls.py
from django.urls import path
from . import views

app_name = 'domain_check'

urlpatterns = [
    path('domain_check/', views.domain_check_page, name='domain_check_page'),
]

form/urls.py
from django.urls import path
from .views import *

app_name = 'form'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]

ftp_storage/urls.py
from django.urls import path
from . import views

app_name = 'ftp_storage'

urlpatterns = [
    path('', views.ftp_page, name='ftp_page'),

]

host_page/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'host_page'

urlpatterns = [
    path('virtual_hosting/', views.virtual_host, name='host'),
    path('vps-hosting/', views.vps_hosting_view, name='vps_hosting_view'),
    path('cloud-hosting/', views.cloud_hosting_view, name='cloud_hosting_view'),

]

hosting/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'hosting'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('form/', include('form.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('host/', include('host_page.urls')),
    path('ftp/', include('ftp_storage.urls')),
    path('', include('ab_cu_t.urls')),
    path('', include('domain_check.urls')),
    path('', include('contact.urls')),

]

contact/models.py
from django.db import models

# Create your models here.


class ContactMessage(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=100)
    message = models.TextField()

    def __str__(self):
        return self.name

contact/forms.py
from django import forms
from .models import ContactMessage

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'email', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'int-in'}),
            'email': forms.EmailInput(attrs={'class': 'int-in'}),
            'message': forms.Textarea(attrs={'rows': 6}),
        }

contact/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.conf import settings
from .forms import ContactForm


def contact_us_page(request):
    # return render(request, 'contact/contact_us.html')
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            send_mail(
                'Повідомлення від користувача',
                f'Ім\'я: {name}\nЕлектронна адреса: {email}\nПовідомлення: {message}',
                settings.DEFAULT_FROM_EMAIL,
                [email],
                fail_silently=False,
            )
            form.save()
            return redirect('contact:contact_us_page')
    else:
        form = ContactForm()

    return render(request, 'contact/contact_us.html', {'form': form})

contact/templates/contact/contact_us.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Зв'зок з нами</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/logo_small_2.png'%}" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <!-- Jquery Library -->
    <script
      src="https://code.jquery.com/jquery-3.6.3.min.js"
      integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
      crossorigin="anonymous" ></script>
    <!-- Linking BoxIcon for Icon -->
    <link
      href="https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css"
      rel="stylesheet" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <script type="text/javascript" src="{% static 'js/crisp.js' %}"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
      integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer">
    </script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"
      integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer">
    </script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/odometer.js/0.4.7/odometer.min.js"
      integrity="sha512-v3fZyWIk7kh9yGNQZf1SnSjIxjAKsYbg6UQ+B+QxAZqJQLrN3jMjrdNwcxV6tis6S0s1xyVDZrDz9UoRLfRpWw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css"
      integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css"
      integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A=="
      crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/odometer.js/0.4.7/themes/odometer-theme-default.css"
      integrity="sha512-kMPqFnKueEwgQFzXLEEl671aHhQqrZLS5IP3HzqdfozaST/EgU+/wkM07JCmXFAt9GO810I//8DBonsJUzGQsQ=="
      crossorigin="anonymous" referrerpolicy="no-referrer"/>
  </head>
  <body>
    <nav id="main-nav" class="blur">
      <div class="logo">Web-Tech</div>
      <label for="btn" class="icon">
        <span class="fa fa-bars"></span>
      </label>
      <input type="checkbox" id="btn" />
      <ul>
        <li class="trans_li"><a href="{% url 'main' %}">Головна</a></li>
        <li class="trans_li">
          <label for="btn-1" class="show">Домен +</label>
          <a>Домен</a>
          <input type="checkbox" id="btn-1" />
          <ul>
            <li><a href="{% url 'domain_check:domain_check_page' %}">Перевірка домену</a></li>
          </ul>
        </li>
        <li class="trans_li">
          <label for="btn-2" class="show">Хостинг +</label>
          <a>Хостинг</a>
          <input type="checkbox" id="btn-2" />
          <ul>
            <li><a href="{% url 'host_page:host' %}">Віртуальний-хостинг</a></li>
            <li><a href="{% url 'host_page:vps_hosting_view' %}"> VPS-хостинг</a></li>
            <li><a href="{% url 'host_page:cloud_hosting_view' %}">Хмарний хостинг</a></li>
          </ul>
        </li>
        <li class="trans_li">
          <label for="btn-3" class="show">Сервіс +</label>
          <a>Сервіс</a>
          <input type="checkbox" id="btn-3" />
          <ul>
            <li><a href="{% url 'ftp_storage:ftp_page' %}">FTP-сховище</a></li>
          </ul>
        </li>
        <li class="trans_li">
          <label for="btn-4" class="show">Про нас +</label>
          <a>Про нас</a>
          <input type="checkbox" id="btn-4" />
          <ul>
            <li><a href="{% url 'ab_cu_t:faq_page' %}"> FAQ (часті запитання)</a></li>
            <li>
              <a href="{% url 'ab_cu_t:privacy_policy' %}"> Політика конфіденційності </a>
            </li>
          </ul>
        </li>
        <li class="trans_li"><a href="{% url 'contact:contact_us_page' %}">Контакти</a></li>
        {% if user.is_authenticated %}
          <li class="trans_li">
            <label for="btn-5" class="show cent_sh"><a class="sign_in">{{ user.username }} +</a></label>
          <a class="sign_in">{{ user.username }}</a>
          <input type="checkbox" id="btn-5" />
          <ul class="cent_sh">
            <li><a>Кабінет</a></li>
            <li><a href="{% url 'form:logout' %}">Вийти</a></li>
          </ul>
          </li>
        {% else %}
          <li class="trans_li"><a href="{% url 'form:login' %}" class="sign_in">Увійти</a></li>
        {% endif %}

      </ul>
    </nav>
    <div class="container-contact-us">
      <h1 class="brand">
        <span>Зв'яжіться з нами</span>
      </h1>
      <div class="wrapper-contact-us">
        <div class="company-info">
          <h3>Web-Tech</h3>
          <ul>
            <li>
              <i class="fas fa-map-marker-alt fa-spin fa-lg"></i>
              <a
                href="https://maps.app.goo.gl/gzwUXZ359wNdZYrRA"
                target="_blank"
                >Vovchynetska St, 223, Ivano-Frankivsk</a
              >
            </li>
            <li>
              <i class="fas fa-mobile-alt fa-spin fa-lg"></i>
              <a href="tel:+0984871113" class="email-link">(098) 487-1113</a>
            </li>
            <li>
              <i class="fas fa-envelope fa-spin fa-lg"></i>
              <a
                href="https://mail.google.com/mail/?view=cm&fs=1&to=pavlokolo3diy@gmail.com"
                target="_blank"
                class="email-link"
                >pavlokolo3diy@gmail.com</a
              >
            </li>
          </ul>
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4130.545276152364!2d24.729447427311207!3d48.941553507052696!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4730c19a4a65e427%3A0xeb6f29186c63340!2sKoledzh%20Elektronnykh%20Pryladiv!5e0!3m2!1sen!2sua!4v1714562433056!5m2!1sen!2sua"
            style="border: 0"
            allowfullscreen=""
            loading="lazy"
            referrerpolicy="no-referrer-when-downgrade">
          </iframe>
        </div>
        <div class="contact">
          <h3></h3>
          <form id="contact-form" method="post">
            {% csrf_token %}
            <p>
              <label for="id_name">Ім'я:</label>
              {{ form.name }}
            </p>
            <p>
              <label for="id_email">Електронна пошта:</label>
              {{ form.email }}
            </p>
            <p class="full">
              <label for="id_message">Повідомлення:</label>
              {{ form.message }}
            </p>
            <p class="full">
              <button type="submit">Відправити</button>
            </p>
          </form>

        </div>
      </div>
    </div>
    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="footer-col">
            <h4>Про нас</h4>
            Web-Tech пропонує чудовий, надійний і доступний веб-хостинг для
            окремих осіб і малих компаній у всьому світі.
          </div>
          <div class="footer-col">
            <h4>Компанія</h4>
            <ul>
              <li><a href="{% url 'main' %}">Головна</a></li>
              <li><a href="{% url 'domain_check:domain_check_page' %}">Перевірка домену</a></li>
              <li><a href="{% url 'ftp_storage:ftp_page' %}">FTP-сховище</a></li>
            </ul>
          </div>
          <div class="footer-col">
            <h4>Допомога</h4>
            <ul>
              <li><a href="{% url 'ab_cu_t:faq_page' %}">FAQ</a></li>
              <li><a href="{% url 'ab_cu_t:privacy_policy' %}">Політика конфіденційності</a></li>
              <li><a href="{% url 'contact:contact_us_page' %}">Контакти</a></li>
            </ul>
          </div>
          <div class="footer-col">
                  <h4>Хостинг</h4>
                  <ul>
                    <li><a href="{% url 'host_page:host' %}">Віртуальний-хостинг</a></li>
                    <li><a href="{% url 'host_page:vps_hosting_view' %}"> VPS-хостинг</a></li>
                    <li><a href="{% url 'host_page:cloud_hosting_view' %}">Хмарний хостинг</a></li>
                  </ul>
          </div>
          <div class="footer-col">
            <h4>Слідкувати за нами:</h4>
            <div class="social-links">
              <a href="https://www.facebook.com/"
                ><i class="fab fa-facebook-f"></i
              ></a>
              <a href="https://twitter.com/?lang=en"
                ><i class="fab fa-twitter"></i
              ></a>
              <a href="https://www.instagram.com/"
                ><i class="fab fa-instagram"></i
              ></a>
              <a href="https://ua.linkedin.com/"
                ><i class="fab fa-linkedin-in"></i
              ></a>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>