ab_cu_t/urls.py
from django.urls import path
from . import views

app_name = 'ab_cu_t'

urlpatterns = [
    path('faq/', views.faq_page, name='faq_page'),
    path('PrivacyPolicy/', views.privacy_policy, name='privacy_policy'),
]

contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
    path('contact/', views.contact_us_page, name='contact_us_page'),
]

form/urls.py
from django.urls import path
from .views import *

app_name = 'form'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
]

ftp_storage/urls.py
from django.urls import path
from . import views

app_name = 'ftp_storage'

urlpatterns = [
    path('', views.ftp_page, name='ftp_page'),

]

host_page/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'host_page'

urlpatterns = [
    path('virtual_hosting/', views.virtual_host, name='host'),
    path('vps-hosting/', views.vps_hosting_view, name='vps_hosting_view'),
    path('cloud-hosting/', views.cloud_hosting_view, name='cloud_hosting_view'),

]

hosting/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'hosting'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('form/', include('form.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('host/', include('host_page.urls')),
    path('ftp/', include('ftp_storage.urls')),
    path('', include('ab_cu_t.urls')),
    path('', include('domain_check.urls')),
    path('', include('contact.urls')),

]

form/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

form/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from .models import *


class RegisterUserForm(UserCreationForm):
    first_name = forms.CharField(label='Ім`я', widget=forms.TextInput(attrs={'class': 'form-input'}))
    last_name = forms.CharField(label='Прізвище', widget=forms.TextInput(attrs={'class': 'form-input'}))
    username = forms.CharField(label='Логін', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логін', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

form/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import *
from .models import *


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'form/register.html'
    #success_url = reverse_lazy('login')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('main')


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'form/login.html'

    def get_success_url(self):
        return reverse_lazy('main')


def logout_user(request):
    logout(request)
    return redirect('main')

form/templates/form/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Web-Tech</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/logo_small_2.png'%}" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
      integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer">
    </script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"
      integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer">
    </script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/odometer.js/0.4.7/odometer.min.js"
      integrity="sha512-v3fZyWIk7kh9yGNQZf1SnSjIxjAKsYbg6UQ+B+QxAZqJQLrN3jMjrdNwcxV6tis6S0s1xyVDZrDz9UoRLfRpWw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/crisp.js' %}"></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css"
      integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"/>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css"
      integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"/>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/odometer.js/0.4.7/themes/odometer-theme-default.css"
      integrity="sha512-kMPqFnKueEwgQFzXLEEl671aHhQqrZLS5IP3HzqdfozaST/EgU+/wkM07JCmXFAt9GO810I//8DBonsJUzGQsQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"/>
</head>
<body>
    <nav id="main-nav" class="blur">
      <div class="logo">Web-Tech</div>
      <label for="btn" class="icon">
        <span class="fa fa-bars"></span>
      </label>
      <input type="checkbox" id="btn" />
      <ul>
        <li class="trans_li"><a href="{% url 'main' %}">Головна</a></li>
        <li class="trans_li">
          <label for="btn-1" class="show">Домен +</label>
          <a>Домен</a>
          <input type="checkbox" id="btn-1" />
          <ul>
            <li><a href="{% url 'domain_check:domain_check_page' %}">Перевірка домену</a></li>
          </ul>
        </li>
        <li class="trans_li">
          <label for="btn-2" class="show">Хостинг +</label>
          <a>Хостинг</a>
          <input type="checkbox" id="btn-2" />
          <ul>
            <li><a href="{% url 'host_page:host' %}">Віртуальний-хостинг</a></li>
            <li><a href="{% url 'host_page:vps_hosting_view' %}"> VPS-хостинг</a></li>
            <li><a href="{% url 'host_page:cloud_hosting_view' %}">Хмарний хостинг</a></li>
          </ul>
        </li>
        <li class="trans_li">
          <label for="btn-3" class="show">Сервіс +</label>
          <a>Сервіс</a>
          <input type="checkbox" id="btn-3" />
          <ul>
            <li><a href="{% url 'ftp_storage:ftp_page' %}">FTP-сховище</a></li>
          </ul>
        </li>
        <li class="trans_li">
          <label for="btn-4" class="show">Про нас +</label>
          <a>Про нас</a>
          <input type="checkbox" id="btn-4" />
          <ul>
            <li><a href="{% url 'ab_cu_t:faq_page' %}"> FAQ (часті запитання)</a></li>
            <li>
              <a href="{% url 'ab_cu_t:privacy_policy' %}"> Політика конфіденційності </a>
            </li>
          </ul>
        </li>
        <li class="trans_li"><a href="{% url 'contact:contact_us_page' %}">Контакти</a></li>
        {% if user.is_authenticated %}
          <li class="trans_li">
            <label for="btn-5" class="show cent_sh"><a class="sign_in">{{ user.username }} +</a></label>
          <a class="sign_in">{{ user.username }}</a>
          <input type="checkbox" id="btn-5" />
          <ul class="cent_sh">
            <li><a>Кабінет</a></li>
            <li><a href="{% url 'form:logout' %}">Вийти</a></li>
          </ul>
          </li>
        {% else %}
          <li class="trans_li"><a href="{% url 'form:login' %}" class="sign_in">Увійти</a></li>
        {% endif %}

      </ul>
    </nav>

    <div class="login-container">
        <div class="form-box">
            <header>
                <h1 id="title">Логін</h1>
            </header>
            <form method="post">
                {% csrf_token %}

                <input type="text" placeholder="Логін" id="nameField" class="inp-txt-n" name="username">
                <!-- <input type="email" placeholder="Username or Email address" class="inp-txt-e"> -->

                <input type="password" placeholder="Пароль" class="inp-txt-p" name="password">
                <a href="">Забули пароль?</a>
                <input type="submit" value="Login" id="signinBtn" class="inp-txt-b">

                {{ form.errors }}

                <div class="links">
                    <a href=""><img src="{% static 'logos/fb.png' %}" alt=""></a>
                    <a href=""><img src="{% static 'logos/twitter.png' %}" alt=""></a>
                    <a href=""><img src="{% static 'logos/google.png' %}" alt=""></a>
                </div>
                <div class="sign__">
                    <p class="signup">Не учасник? <a href="{% url 'form:register' %}" id="signupBtn"> Зареєструватися</a></p>
                </div>
            </form>
        </div>
    </div>

    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="footer-col">
            <h4>Про нас</h4>
            Web-Tech пропонує чудовий, надійний і доступний веб-хостинг для
            окремих осіб і малих компаній у всьому світі.
          </div>
          <div class="footer-col">
            <h4>Компанія</h4>
            <ul>
              <li><a href="{% url 'main' %}">Головна</a></li>
              <li><a href="{% url 'domain_check:domain_check_page' %}">Перевірка домену</a></li>
              <li><a href="{% url 'ftp_storage:ftp_page' %}">FTP-сховище</a></li>
            </ul>
          </div>
          <div class="footer-col">
            <h4>Допомога</h4>
            <ul>
              <li><a href="{% url 'ab_cu_t:faq_page' %}">FAQ</a></li>
              <li><a href="{% url 'ab_cu_t:privacy_policy' %}">Політика конфіденційності</a></li>
              <li><a href="{% url 'contact:contact_us_page' %}">Контакти</a></li>
            </ul>
          </div>
          <div class="footer-col">
                  <h4>Хостинг</h4>
                  <ul>
                    <li><a href="{% url 'host_page:host' %}">Віртуальний-хостинг</a></li>
                    <li><a href="{% url 'host_page:vps_hosting_view' %}"> VPS-хостинг</a></li>
                    <li><a href="{% url 'host_page:cloud_hosting_view' %}">Хмарний хостинг</a></li>
                  </ul>
          </div>
          <div class="footer-col">
            <h4>Слідкувати за нами:</h4>
            <div class="social-links">
              <a href="https://www.facebook.com/"
                ><i class="fab fa-facebook-f"></i
              ></a>
              <a href="https://twitter.com/?lang=en"
                ><i class="fab fa-twitter"></i
              ></a>
              <a href="https://www.instagram.com/"
                ><i class="fab fa-instagram"></i
              ></a>
              <a href="https://ua.linkedin.com/"
                ><i class="fab fa-linkedin-in"></i
              ></a>
            </div>
          </div>
        </div>
      </div>
    </footer>
</body>
</html>

form/templates/form/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Web-Tech</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/logo_small_2.png'%}" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
      integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer">
    </script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"
      integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer">
    </script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/odometer.js/0.4.7/odometer.min.js"
      integrity="sha512-v3fZyWIk7kh9yGNQZf1SnSjIxjAKsYbg6UQ+B+QxAZqJQLrN3jMjrdNwcxV6tis6S0s1xyVDZrDz9UoRLfRpWw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/crisp.js' %}"></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css"
      integrity="sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"/>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css"
      integrity="sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"/>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/odometer.js/0.4.7/themes/odometer-theme-default.css"
      integrity="sha512-kMPqFnKueEwgQFzXLEEl671aHhQqrZLS5IP3HzqdfozaST/EgU+/wkM07JCmXFAt9GO810I//8DBonsJUzGQsQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"/>
</head>
<body>
<nav id="main-nav" class="blur">
      <div class="logo">Web-Tech</div>
      <label for="btn" class="icon">
        <span class="fa fa-bars"></span>
      </label>
      <input type="checkbox" id="btn" />
      <ul>
        <li class="trans_li"><a href="{% url 'main' %}">Головна</a></li>
        <li class="trans_li">
          <label for="btn-1" class="show">Домен +</label>
          <a>Домен</a>
          <input type="checkbox" id="btn-1" />
          <ul>
            <li><a href="{% url 'domain_check:domain_check_page' %}">Перевірка домену</a></li>
          </ul>
        </li>
        <li class="trans_li">
          <label for="btn-2" class="show">Хостинг +</label>
          <a>Хостинг</a>
          <input type="checkbox" id="btn-2" />
          <ul>
            <li><a href="{% url 'host_page:host' %}">Віртуальний-хостинг</a></li>
            <li><a href="{% url 'host_page:vps_hosting_view' %}"> VPS-хостинг</a></li>
            <li><a href="{% url 'host_page:cloud_hosting_view' %}">Хмарний хостинг</a></li>
          </ul>
        </li>
        <li class="trans_li">
          <label for="btn-3" class="show">Сервіс +</label>
          <a>Сервіс</a>
          <input type="checkbox" id="btn-3" />
          <ul>
            <li><a href="{% url 'ftp_storage:ftp_page' %}">FTP-сховище</a></li>
          </ul>
        </li>
        <li class="trans_li">
          <label for="btn-4" class="show">Про нас +</label>
          <a>Про нас</a>
          <input type="checkbox" id="btn-4" />
          <ul>
            <li><a href="{% url 'ab_cu_t:faq_page' %}"> FAQ (часті запитання)</a></li>
            <li>
              <a href="{% url 'ab_cu_t:privacy_policy' %}"> Політика конфіденційності </a>
            </li>
          </ul>
        </li>
        <li class="trans_li"><a href="{% url 'contact:contact_us_page' %}">Контакти</a></li>
        {% if user.is_authenticated %}
          <li class="trans_li">
            <label for="btn-5" class="show cent_sh"><a class="sign_in">{{ user.username }} +</a></label>
          <a class="sign_in">{{ user.username }}</a>
          <input type="checkbox" id="btn-5" />
          <ul class="cent_sh">
            <li><a>Кабінет</a></li>
            <li><a href="{% url 'form:logout' %}">Вийти</a></li>
          </ul>
          </li>
        {% else %}
          <li class="trans_li"><a href="{% url 'form:login' %}" class="sign_in">Увійти</a></li>
        {% endif %}

      </ul>
    </nav>
    <div class="login-container">
        <div class="form-box">
            <header>
                <h1 id="title">Реєстрація</h1>
            </header>
            <form method="post">
                {% csrf_token %}

                <input type="text" placeholder="Ім'я" id="FrstNameField" class="inp-txt-n" name="first_name">
                <input type="text" placeholder="Прізвище" id="LadstNameField" class="inp-txt-n" name="last_name">
                <input type="text" placeholder="Логін" id="nameField" class="inp-txt-n" name="username">
                <input type="email" placeholder="Email" class="inp-txt-e" name="email">
                <input type="password" placeholder="Пароль" class="inp-txt-p" name="password1">
                <input type="password" placeholder="Повтор паролю" class="inp-txt-p" name="password2">


<!--                <a href="">Забули пароль?</a>-->
                <input type="submit" value="Register" id="signinBtn" class="inp-txt-b">

                <div class="links">
                    <a href=""><img src="{% static 'logos/fb.png' %}" alt=""></a>
                    <a href=""><img src="{% static 'logos/twitter.png' %}" alt=""></a>
                    <a href=""><img src="{% static 'logos/google.png' %}" alt=""></a>
                </div>
                <div class="sign__">
                    <p class="signup">Ви вже учасник? <a href="{% url 'form:login' %}" id="signupBtn"> Увійти</a></p>
                </div>
            </form>
        </div>
    </div>

    <footer class="footer">
      <div class="container">
        <div class="row">
          <div class="footer-col">
            <h4>Про нас</h4>
            Web-Tech пропонує чудовий, надійний і доступний веб-хостинг для
            окремих осіб і малих компаній у всьому світі.
          </div>
          <div class="footer-col">
            <h4>Компанія</h4>
            <ul>
              <li><a href="{% url 'main' %}">Головна</a></li>
              <li><a href="{% url 'domain_check:domain_check_page' %}">Перевірка домену</a></li>
              <li><a href="{% url 'ftp_storage:ftp_page' %}">FTP-сховище</a></li>
            </ul>
          </div>
          <div class="footer-col">
            <h4>Допомога</h4>
            <ul>
              <li><a href="{% url 'ab_cu_t:faq_page' %}">FAQ</a></li>
              <li><a href="{% url 'ab_cu_t:privacy_policy' %}">Політика конфіденційності</a></li>
              <li><a href="{% url 'contact:contact_us_page' %}">Контакти</a></li>
            </ul>
          </div>
          <div class="footer-col">
                  <h4>Хостинг</h4>
                  <ul>
                    <li><a href="{% url 'host_page:host' %}">Віртуальний-хостинг</a></li>
                    <li><a href="{% url 'host_page:vps_hosting_view' %}"> VPS-хостинг</a></li>
                    <li><a href="{% url 'host_page:cloud_hosting_view' %}">Хмарний хостинг</a></li>
                  </ul>
          </div>
          <div class="footer-col">
            <h4>Слідкувати за нами:</h4>
            <div class="social-links">
              <a href="https://www.facebook.com/"
                ><i class="fab fa-facebook-f"></i
              ></a>
              <a href="https://twitter.com/?lang=en"
                ><i class="fab fa-twitter"></i
              ></a>
              <a href="https://www.instagram.com/"
                ><i class="fab fa-instagram"></i
              ></a>
              <a href="https://ua.linkedin.com/"
                ><i class="fab fa-linkedin-in"></i
              ></a>
            </div>
          </div>
        </div>
      </div>
    </footer>
</body>
</html>